# Generated by Django 2.2.7 on 2019-11-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20191116_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='hashtag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
